### PR TITLE
Add command to print version

### PR DESCRIPTION
**Pull request by hooksie1**
Adds command to print version based on tags.

### CODE REVIEW

**Comment by mikhailswift** [comment]
Oh, hey! A familiar face!

**Comment by mikhailswift** [comment]
This looks pretty good!  Some thoughts I've had after thinking about this feature a bit:

* This will need to tie into our go-releaser workflow.  Thinking about go-releaser makes me think we may want to remove the Makefile since it's not actually used in our pipelines and is somewhat misleading -- additionally I know the go team has recommended against the use of Makefiles in favor of just calling `go build`.  The Makefile stuff is out of scope for this PR but we will want to make sure this works with the go-releaser workflow as part of this PR.

* We need to think about what version we report for builds that weren't built on the tagged commit.  For instance if I built this locally on this branch's HEAD it reports v0.1.1, our last tagged release.  I don't think we'll want to report v0.1.1 unless it was built on the actual tagged commit.  In previous projects I've defaulted to reporting `v0.0.0-dev-$SHORTHASH` in these cases, but perhaps the last tagged version with some metadata is perferable -- `v0.1.1-dev-47af3351` for the current HEAD of this branch, for example.

**Comment by mikhailswift** [comment]
The default `git describe --tags` may be a fine output

`v0.1.1-4-g47af335`

**Comment by mikhailswift** [comment]
Only other thing would be to run `make docgen` to generate the markdown for the new command

**Comment by hooksie1** [comment]
Ah ok. Thanks for the input. I'll go through all of this tonight!

**Comment by hooksie1** [comment]
Ok. I restored the Makefile and then added the ldflag to goreleaser. Looks like goreleaser already had values for the git tag and short hash so I just used those. I apologize for the extra commit. Hopefully we can just squash and merge to keep it clean.

**Review by mikhailswift — APPROVED** [review]
Thanks!

**Pull request merged**
