### PR TITLE
chore: update archivst -> archivista

### PR DESCRIPTION
**Pull request by mikhailswift**

### CODE REVIEW

**Comment by mikhailswift** [comment]
we may want to get https://github.com/testifysec/go-witness/pull/34 in first

**Review by kriscoleman — APPROVED** [review]

**Comment by colek42** [comment]
This is going to be a breaking change unless we depricate

**Comment by colek42** [comment]
requires https://gitlab.com/testifysec/internal-infra/deployments/-/merge_requests/7

**Comment by colek42** [comment]
This is going to break everything in our infra due to the new flag name.  Can we add an alias deprecate the old one please

**Comment by mikhailswift** [comment]
@colek42 this is ready now.

**Review by colek42 — APPROVED** [review]

**Pull request merged**
